// Country list (English + Russian + Uzbek) used for the citizenship combobox.
// Common ISO countries. Russian names are used in the UI by default.
export type Country = { code: string; ru: string; en: string; uz: string; flag: string };

export const COUNTRIES: Country[] = [
  { code: 'UZ', ru: 'Узбекистан', en: 'Uzbekistan', uz: "O'zbekiston", flag: '🇺🇿' },
  { code: 'RU', ru: 'Россия', en: 'Russia', uz: 'Rossiya', flag: '🇷🇺' },
  { code: 'KZ', ru: 'Казахстан', en: 'Kazakhstan', uz: "Qozog'iston", flag: '🇰🇿' },
  { code: 'KG', ru: 'Кыргызстан', en: 'Kyrgyzstan', uz: "Qirg'iziston", flag: '🇰🇬' },
  { code: 'TJ', ru: 'Таджикистан', en: 'Tajikistan', uz: 'Tojikiston', flag: '🇹🇯' },
  { code: 'TM', ru: 'Туркменистан', en: 'Turkmenistan', uz: 'Turkmaniston', flag: '🇹🇲' },
  { code: 'AF', ru: 'Афганистан', en: 'Afghanistan', uz: "Afg'oniston", flag: '🇦🇫' },
  { code: 'AZ', ru: 'Азербайджан', en: 'Azerbaijan', uz: 'Ozarbayjon', flag: '🇦🇿' },
  { code: 'AM', ru: 'Армения', en: 'Armenia', uz: 'Armaniston', flag: '🇦🇲' },
  { code: 'BY', ru: 'Беларусь', en: 'Belarus', uz: 'Belarus', flag: '🇧🇾' },
  { code: 'GE', ru: 'Грузия', en: 'Georgia', uz: 'Gruziya', flag: '🇬🇪' },
  { code: 'MD', ru: 'Молдова', en: 'Moldova', uz: 'Moldova', flag: '🇲🇩' },
  { code: 'UA', ru: 'Украина', en: 'Ukraine', uz: 'Ukraina', flag: '🇺🇦' },
  { code: 'TR', ru: 'Турция', en: 'Turkey', uz: 'Turkiya', flag: '🇹🇷' },
  { code: 'CN', ru: 'Китай', en: 'China', uz: 'Xitoy', flag: '🇨🇳' },
  { code: 'IN', ru: 'Индия', en: 'India', uz: 'Hindiston', flag: '🇮🇳' },
  { code: 'PK', ru: 'Пакистан', en: 'Pakistan', uz: 'Pokiston', flag: '🇵🇰' },
  { code: 'IR', ru: 'Иран', en: 'Iran', uz: 'Eron', flag: '🇮🇷' },
  { code: 'IQ', ru: 'Ирак', en: 'Iraq', uz: 'Iroq', flag: '🇮🇶' },
  { code: 'SA', ru: 'Саудовская Аравия', en: 'Saudi Arabia', uz: 'Saudiya Arabistoni', flag: '🇸🇦' },
  { code: 'AE', ru: 'ОАЭ', en: 'United Arab Emirates', uz: 'BAA', flag: '🇦🇪' },
  { code: 'QA', ru: 'Катар', en: 'Qatar', uz: 'Qatar', flag: '🇶🇦' },
  { code: 'KW', ru: 'Кувейт', en: 'Kuwait', uz: 'Quvayt', flag: '🇰🇼' },
  { code: 'IL', ru: 'Израиль', en: 'Israel', uz: 'Isroil', flag: '🇮🇱' },
  { code: 'JO', ru: 'Иордания', en: 'Jordan', uz: 'Iordaniya', flag: '🇯🇴' },
  { code: 'LB', ru: 'Ливан', en: 'Lebanon', uz: 'Livan', flag: '🇱🇧' },
  { code: 'SY', ru: 'Сирия', en: 'Syria', uz: 'Suriya', flag: '🇸🇾' },
  { code: 'EG', ru: 'Египет', en: 'Egypt', uz: 'Misr', flag: '🇪🇬' },
  { code: 'JP', ru: 'Япония', en: 'Japan', uz: 'Yaponiya', flag: '🇯🇵' },
  { code: 'KR', ru: 'Южная Корея', en: 'South Korea', uz: 'Janubiy Koreya', flag: '🇰🇷' },
  { code: 'KP', ru: 'Северная Корея', en: 'North Korea', uz: 'Shimoliy Koreya', flag: '🇰🇵' },
  { code: 'MN', ru: 'Монголия', en: 'Mongolia', uz: "Mo'g'uliston", flag: '🇲🇳' },
  { code: 'VN', ru: 'Вьетнам', en: 'Vietnam', uz: 'Vyetnam', flag: '🇻🇳' },
  { code: 'TH', ru: 'Таиланд', en: 'Thailand', uz: 'Tailand', flag: '🇹🇭' },
  { code: 'ID', ru: 'Индонезия', en: 'Indonesia', uz: 'Indoneziya', flag: '🇮🇩' },
  { code: 'MY', ru: 'Малайзия', en: 'Malaysia', uz: 'Malayziya', flag: '🇲🇾' },
  { code: 'SG', ru: 'Сингапур', en: 'Singapore', uz: 'Singapur', flag: '🇸🇬' },
  { code: 'PH', ru: 'Филиппины', en: 'Philippines', uz: 'Filippin', flag: '🇵🇭' },
  { code: 'BD', ru: 'Бангладеш', en: 'Bangladesh', uz: 'Bangladesh', flag: '🇧🇩' },
  { code: 'LK', ru: 'Шри-Ланка', en: 'Sri Lanka', uz: 'Shri-Lanka', flag: '🇱🇰' },
  { code: 'NP', ru: 'Непал', en: 'Nepal', uz: 'Nepal', flag: '🇳🇵' },
  { code: 'GB', ru: 'Великобритания', en: 'United Kingdom', uz: 'Buyuk Britaniya', flag: '🇬🇧' },
  { code: 'US', ru: 'США', en: 'United States', uz: 'AQSH', flag: '🇺🇸' },
  { code: 'CA', ru: 'Канада', en: 'Canada', uz: 'Kanada', flag: '🇨🇦' },
  { code: 'MX', ru: 'Мексика', en: 'Mexico', uz: 'Meksika', flag: '🇲🇽' },
  { code: 'BR', ru: 'Бразилия', en: 'Brazil', uz: 'Braziliya', flag: '🇧🇷' },
  { code: 'AR', ru: 'Аргентина', en: 'Argentina', uz: 'Argentina', flag: '🇦🇷' },
  { code: 'DE', ru: 'Германия', en: 'Germany', uz: 'Germaniya', flag: '🇩🇪' },
  { code: 'FR', ru: 'Франция', en: 'France', uz: 'Fransiya', flag: '🇫🇷' },
  { code: 'IT', ru: 'Италия', en: 'Italy', uz: 'Italiya', flag: '🇮🇹' },
  { code: 'ES', ru: 'Испания', en: 'Spain', uz: 'Ispaniya', flag: '🇪🇸' },
  { code: 'PT', ru: 'Португалия', en: 'Portugal', uz: 'Portugaliya', flag: '🇵🇹' },
  { code: 'NL', ru: 'Нидерланды', en: 'Netherlands', uz: 'Niderlandiya', flag: '🇳🇱' },
  { code: 'BE', ru: 'Бельгия', en: 'Belgium', uz: 'Belgiya', flag: '🇧🇪' },
  { code: 'CH', ru: 'Швейцария', en: 'Switzerland', uz: 'Shveytsariya', flag: '🇨🇭' },
  { code: 'AT', ru: 'Австрия', en: 'Austria', uz: 'Avstriya', flag: '🇦🇹' },
  { code: 'PL', ru: 'Польша', en: 'Poland', uz: 'Polsha', flag: '🇵🇱' },
  { code: 'CZ', ru: 'Чехия', en: 'Czech Republic', uz: 'Chexiya', flag: '🇨🇿' },
  { code: 'SK', ru: 'Словакия', en: 'Slovakia', uz: 'Slovakiya', flag: '🇸🇰' },
  { code: 'HU', ru: 'Венгрия', en: 'Hungary', uz: 'Vengriya', flag: '🇭🇺' },
  { code: 'RO', ru: 'Румыния', en: 'Romania', uz: 'Ruminiya', flag: '🇷🇴' },
  { code: 'BG', ru: 'Болгария', en: 'Bulgaria', uz: 'Bolgariya', flag: '🇧🇬' },
  { code: 'GR', ru: 'Греция', en: 'Greece', uz: 'Gretsiya', flag: '🇬🇷' },
  { code: 'SE', ru: 'Швеция', en: 'Sweden', uz: 'Shvetsiya', flag: '🇸🇪' },
  { code: 'NO', ru: 'Норвегия', en: 'Norway', uz: 'Norvegiya', flag: '🇳🇴' },
  { code: 'FI', ru: 'Финляндия', en: 'Finland', uz: 'Finlyandiya', flag: '🇫🇮' },
  { code: 'DK', ru: 'Дания', en: 'Denmark', uz: 'Daniya', flag: '🇩🇰' },
  { code: 'IE', ru: 'Ирландия', en: 'Ireland', uz: 'Irlandiya', flag: '🇮🇪' },
  { code: 'IS', ru: 'Исландия', en: 'Iceland', uz: 'Islandiya', flag: '🇮🇸' },
  { code: 'EE', ru: 'Эстония', en: 'Estonia', uz: 'Estoniya', flag: '🇪🇪' },
  { code: 'LV', ru: 'Латвия', en: 'Latvia', uz: 'Latviya', flag: '🇱🇻' },
  { code: 'LT', ru: 'Литва', en: 'Lithuania', uz: 'Litva', flag: '🇱🇹' },
  { code: 'RS', ru: 'Сербия', en: 'Serbia', uz: 'Serbiya', flag: '🇷🇸' },
  { code: 'HR', ru: 'Хорватия', en: 'Croatia', uz: 'Xorvatiya', flag: '🇭🇷' },
  { code: 'AU', ru: 'Австралия', en: 'Australia', uz: 'Avstraliya', flag: '🇦🇺' },
  { code: 'NZ', ru: 'Новая Зеландия', en: 'New Zealand', uz: 'Yangi Zelandiya', flag: '🇳🇿' },
  { code: 'ZA', ru: 'ЮАР', en: 'South Africa', uz: 'JAR', flag: '🇿🇦' },
  { code: 'NG', ru: 'Нигерия', en: 'Nigeria', uz: 'Nigeriya', flag: '🇳🇬' },
  { code: 'KE', ru: 'Кения', en: 'Kenya', uz: 'Keniya', flag: '🇰🇪' },
  { code: 'MA', ru: 'Марокко', en: 'Morocco', uz: 'Marokash', flag: '🇲🇦' },
];

export function countryLabel(c: Country, lang: string): string {
  if (lang === 'en') return c.en;
  if (lang === 'uz') return c.uz;
  return c.ru;
}
