/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperuserRouteImport } from './routes/superuser'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperuserIndexRouteImport } from './routes/superuser.index'
import { Route as SuperuserHistoryRouteImport } from './routes/superuser.history'
import { Route as SuperuserAdminsRouteImport } from './routes/superuser.admins'
import { Route as BookingsIdDeleteRouteImport } from './routes/bookings.$id.delete'

const SuperuserRoute = SuperuserRouteImport.update({
  id: '/superuser',
  path: '/superuser',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperuserIndexRoute = SuperuserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperuserRoute,
} as any)
const SuperuserHistoryRoute = SuperuserHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SuperuserRoute,
} as any)
const SuperuserAdminsRoute = SuperuserAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperuserRoute,
} as any)
const BookingsIdDeleteRoute = BookingsIdDeleteRouteImport.update({
  id: '/bookings/$id/delete',
  path: '/bookings/$id/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/director': typeof DirectorRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/superuser': typeof SuperuserRouteWithChildren
  '/superuser/admins': typeof SuperuserAdminsRoute
  '/superuser/history': typeof SuperuserHistoryRoute
  '/superuser/': typeof SuperuserIndexRoute
  '/bookings/$id/delete': typeof BookingsIdDeleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/director': typeof DirectorRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/superuser/admins': typeof SuperuserAdminsRoute
  '/superuser/history': typeof SuperuserHistoryRoute
  '/superuser': typeof SuperuserIndexRoute
  '/bookings/$id/delete': typeof BookingsIdDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/director': typeof DirectorRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/superuser': typeof SuperuserRouteWithChildren
  '/superuser/admins': typeof SuperuserAdminsRoute
  '/superuser/history': typeof SuperuserHistoryRoute
  '/superuser/': typeof SuperuserIndexRoute
  '/bookings/$id/delete': typeof BookingsIdDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/director'
    | '/login'
    | '/manager'
    | '/superuser'
    | '/superuser/admins'
    | '/superuser/history'
    | '/superuser/'
    | '/bookings/$id/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/director'
    | '/login'
    | '/manager'
    | '/superuser/admins'
    | '/superuser/history'
    | '/superuser'
    | '/bookings/$id/delete'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/director'
    | '/login'
    | '/manager'
    | '/superuser'
    | '/superuser/admins'
    | '/superuser/history'
    | '/superuser/'
    | '/bookings/$id/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DirectorRoute: typeof DirectorRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  SuperuserRoute: typeof SuperuserRouteWithChildren
  BookingsIdDeleteRoute: typeof BookingsIdDeleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superuser': {
      id: '/superuser'
      path: '/superuser'
      fullPath: '/superuser'
      preLoaderRoute: typeof SuperuserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superuser/': {
      id: '/superuser/'
      path: '/'
      fullPath: '/superuser/'
      preLoaderRoute: typeof SuperuserIndexRouteImport
      parentRoute: typeof SuperuserRoute
    }
    '/superuser/history': {
      id: '/superuser/history'
      path: '/history'
      fullPath: '/superuser/history'
      preLoaderRoute: typeof SuperuserHistoryRouteImport
      parentRoute: typeof SuperuserRoute
    }
    '/superuser/admins': {
      id: '/superuser/admins'
      path: '/admins'
      fullPath: '/superuser/admins'
      preLoaderRoute: typeof SuperuserAdminsRouteImport
      parentRoute: typeof SuperuserRoute
    }
    '/bookings/$id/delete': {
      id: '/bookings/$id/delete'
      path: '/bookings/$id/delete'
      fullPath: '/bookings/$id/delete'
      preLoaderRoute: typeof BookingsIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperuserRouteChildren {
  SuperuserAdminsRoute: typeof SuperuserAdminsRoute
  SuperuserHistoryRoute: typeof SuperuserHistoryRoute
  SuperuserIndexRoute: typeof SuperuserIndexRoute
}

const SuperuserRouteChildren: SuperuserRouteChildren = {
  SuperuserAdminsRoute: SuperuserAdminsRoute,
  SuperuserHistoryRoute: SuperuserHistoryRoute,
  SuperuserIndexRoute: SuperuserIndexRoute,
}

const SuperuserRouteWithChildren = SuperuserRoute._addFileChildren(
  SuperuserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DirectorRoute: DirectorRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  SuperuserRoute: SuperuserRouteWithChildren,
  BookingsIdDeleteRoute: BookingsIdDeleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
